// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Generated by script/gen-cat-data.js — DO NOT EDIT BY HAND.
/// Art tables, value->trait maps, palettes and names for the Quantum Cats renderer.
/// DNA layout (MSB-first, 38 bits):
///   earShape[2] earInner[2] whiskerStyle[2] whiskerColor[1] eyeShape[2]
///   eyeColor[3] fur[4] pattern[3] accessory[3] bg[3] schrodinger[5] interference[8]
library CatData {
    // 24x24 base cat, row-major chars
    bytes internal constant GRID =
        "..............................o.........o............ofo.......ofo...........ofio.....oifo...........ofiio...oiifo...........offfooooofffo..........offffffffffffffo........offffffffffffffo........offffffffffffffo........offffffffffffffo........ofpeffffffpefffo........offffffffffffffo......wwoffffffffffffffoww......offfffnnfffffffo......wwofffffmffffffffoww.......offffffffffffo...........offffffffffo...............offffo..................offffo................offffffffo............offffffffffffo.........offffffffffffffo........offffffffffffffo........offffffffffffffo....";

    // 24x24 superposition box
    bytes internal constant BOX =
        "............................................................................oooooooooooooooo.......oBBBBBBBBTTBBBBBBo......oBBBBBBBBTTBBBBBBo......oooooooooooooooooo......oFFFFFFFFTTFFFFFFo......oFFFFFFFFTTFFFFFFo......oFFFFQQQQQQFFFFFFo......oFFFQQFFFFQQFFFFFo......oFFFFFFFFFQQFFFFFo......oFFFFFFFFQQFFFFFFo......oFFFFFFFQQFFFFFFFo......oFFFFFFFFFFFFFFFFo......oFFFFFFFQQFFFFFFFo......oFFFFFFFQQFFFFFFFo......oFFFFFFFFFFFFFFFFo......oooooooooooooooooo...........................................................................................................................";

    // pixel overlays: packed (y, x, charCode) triplets
    bytes internal constant EAR_ROUNDED = hex"02056f02116f020666021066020766020f6602086f020e6f03056f03116f030666031066030769030f6903086f030e6f04056f04116f040666041066040769040f69040869040e6904096f040d6f";
    bytes internal constant EAR_FOLDED = hex"03056f03116f03066f03106f03076f030f6f03086f030e6f04056f04116f040666041066040769040f6904086f040e6f04096f040d6f";
    bytes internal constant WHISK_CLASSIC = hex"0c02770c03770c14770c15770e02770e03770e14770e1577";
    bytes internal constant WHISK_LONG = hex"0c00770c01770c02770c03770c14770c15770c16770c17770e00770e01770e02770e03770e14770e15770e16770e1777";
    bytes internal constant EYE_ROUND = hex"0a06700a07650a0e700a0f65";
    bytes internal constant EYE_WIDE = hex"0a06700a07650b06650b07650a0e700a0f650b0e650b0f65";
    bytes internal constant EYE_SLIT = hex"0a06650a07700b06650b07700a0e700a0f650b0e700b0f65";
    bytes internal constant EYEH_ROUND = hex"0a0f45";
    bytes internal constant EYEH_WIDE = hex"0a0f450b0e450b0f45";
    bytes internal constant EYEH_SLIT = hex"0a0f450b0f45";
    bytes internal constant PAT_TUXEDO = hex"0d086c0d096c0d0c6c0d0d6c0e086c0e096c0e0b6c0e0c6c0e0d6c0f086c0f096c0f0a6c0f0b6c0f0c6c0f0d6c130a6c130b6c130c6c130d6c14096c140a6c140b6c140c6c140d6c140e6c15096c150a6c150b6c150c6c150d6c150e6c16096c160a6c160b6c160c6c160d6c160e6c17096c170a6c170b6c170c6c170d6c170e6c";
    bytes internal constant PAT_PATCH = hex"090d64090e64090f640910640a0d640a10640b0d640b0e640b0f640b1064140664140764150664150764150864160764";
    bytes internal constant PAT_TIGER = hex"070964070b64070d64080964080b64080d64090964090b64090d640b05640b06640c05640b11640b10640c1164150664160664170664151164161164171164130964140964150964160964170964130e64140e64150e64160e64170e64140b64150b64160b64170b64140c64150c64160c64170c64";
    bytes internal constant PAT_CALICO = hex"060744060844060944060a44070744070844070944070a44080744080844080944080a440b0e640b0f640b10640c0e640c0f640c10640d0f640d1064140644140744150644150744150844160644160744";
    bytes internal constant ACC_HAT = hex"030968030a68030b68030c68030d68040768040868040968040a68040b68040c68040d68040e68040f68041068050648050748050848050948050a48050b48050c48050d48050e48050f48051048051148";
    bytes internal constant ACC_CIG = hex"0f0d630f0e630f0f630f10630f11630f12630f13670d14730c15730a1573";
    bytes internal constant ACC_CROSS = hex"130843130943130a43130b43130c43130d43130e43130f43140b43150a43150b43150c43160b43";
    bytes internal constant ACC_SCARF = hex"110872110972110a72110b72110c72110d72110e72110f72120852120952120a52120b52120c52120d52120e52120f52130c72130d72140c72140d72150c52150d52";

    // raw field value -> option index
    bytes internal constant MAP_EARSHAPE = hex"00000102";
    bytes internal constant MAP_EARINNER = hex"00000102";
    bytes internal constant MAP_WHISKSTYLE = hex"00000102";
    bytes internal constant MAP_EYESHAPE = hex"00000102";
    bytes internal constant MAP_EYECOLOR = hex"0000010102030405";
    bytes internal constant MAP_FUR = hex"00000000000101010202020303040405";
    bytes internal constant MAP_PATTERN = hex"0000000101020304";
    bytes internal constant MAP_ACC = hex"0000010203040506";
    bytes internal constant MAP_BG = hex"0000010203040405";

    // palettes: packed RGB triplets
    // fur: 6 furs x roles [f,d,l,i,n]
    bytes internal constant FUR_PAL = hex"8a8a925c5c64c9c9cff2a7b8e88aa0d98a3da05a24f2d3a7f2b8c6d9708633333c41414a4d4d58c96f86c96f86efe6d8cbbfa9fbf7eff2a7b8e88aa06b4a334f35248a6a4fe8a0a8c98a8ad9a79ab57f70edc9bfc96f86a85560";
    bytes internal constant EYE_PAL = hex"7fd0695fb0ffffd23fff8c3bb98aff7fd069";
    // bg: 6 hues x [base, fringe]
    bytes internal constant BG_PAL = hex"7ba3c290b1cb7a6a8f8f81a0bfa87ec9b5925f8f7a78a08f96637aa67b8f3f35505d556c";
    // beanies: 3 x [main, band]
    bytes internal constant HAT_PAL = hex"3b6ea5274b73a53b3b7327277a5aa554407a";
    bytes internal constant INNER_PAL = hex"b8a7f23a3a44";
    bytes internal constant WHISK_PAL = hex"14141ae8e8e8";
    // fixed chars in order: o p m x W k K c g s D C r R
    bytes internal constant FIXED_CHARS = "opmxWkKcgsDCrR";
    bytes internal constant FIXED_PAL = hex"14141a14141a14141a101218e8f6ffe9e5dab3ac9ce8e8e8ff8c3b9aa3add98a3dd9b23da53b3b7e2c2c";
    // box chars in order: o B F T Q, then bg pair
    bytes internal constant BOX_CHARS = "oBFTQ";
    bytes internal constant BOX_PAL = hex"14141ac9a06ab58a52d9c9a35c3f28";
    bytes internal constant BOX_BG = hex"2622332d2940";

    function earShapeName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "Pointed";
        if (v == 1) return "Rounded";
        if (v == 2) return "Folded";
        return "?";
    }

    function earInnerName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "Pink";
        if (v == 1) return "Lavender";
        if (v == 2) return "Charcoal";
        return "?";
    }

    function whiskerStyleName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "Classic";
        if (v == 1) return "None";
        if (v == 2) return "Long";
        return "?";
    }

    function whiskerColorName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "Dark";
        if (v == 1) return "White";
        return "?";
    }

    function eyeShapeName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "Round";
        if (v == 1) return "Wide";
        if (v == 2) return "Slit";
        return "?";
    }

    function eyeColorName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "Green";
        if (v == 1) return "Blue";
        if (v == 2) return "Amber";
        if (v == 3) return "Copper";
        if (v == 4) return "Violet";
        if (v == 5) return "Heterochromia";
        return "?";
    }

    function furName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "Gray";
        if (v == 1) return "Orange";
        if (v == 2) return "Black";
        if (v == 3) return "Cream";
        if (v == 4) return "Chocolate";
        if (v == 5) return "Sphynx";
        return "?";
    }

    function patternName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "Solid";
        if (v == 1) return "Tuxedo";
        if (v == 2) return "Patch";
        if (v == 3) return "Tiger";
        if (v == 4) return "Calico";
        return "?";
    }

    function accessoryName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "None";
        if (v == 1) return "Beanie Blue";
        if (v == 2) return "Beanie Red";
        if (v == 3) return "Beanie Purple";
        if (v == 4) return "Cigarette";
        if (v == 5) return "Cross Necklace";
        if (v == 6) return "Scarf";
        return "?";
    }

    function bgName(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "Sky";
        if (v == 1) return "Purple";
        if (v == 2) return "Sand";
        if (v == 3) return "Green";
        if (v == 4) return "Rose";
        if (v == 5) return "Dusk";
        return "?";
    }
}
